baseURL = "http://example.org/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Simon Storl-Schulke"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
  # LoveIt theme version
  version = "0.2.X"

[menu]
  [[menu.main]]
    identifier = "about"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "About"
    url = "/about/"
    weight = 1
  
  [[menu.main]]
    identifier = "skills"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Skills"
    url = "/skills/"
    weight = 2
    
  [[menu.main]]
    identifier = "portfolio"
    pre = ""
    post = ""
    name = "Portfolio"
    url = "/portfolio/"
    weight = 3  
    
   [[menu.main]]
    identifier = "demoreel"
    pre = ""
    post = ""
    name = "Demoreel"
    url = "/demoreel/"
    weight = 4
  

  [[menu.main]]
    identifier = "projects"
    pre = ""
    post = ""
    name = "Projects"
    url = "/projects/"
    weight = 5


  [[menu.main]]
    identifier = "musik"
    pre = ""
    post = ""
    name = "Musik"
    url = "/musik/"
    weight = 6

  [[menu.main]]
    identifier = "tutorials"
    pre = ""
    post = ""
    name = "Tutorials"
    url = "/tutorials/"
    weight = 7

  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    weight = 8

[markup]
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false